name: silta
recipe: drupal8

config:
  webroot: web
  via: nginx
  php: '7.2'
  database: mariadb:10.2
  #xdebug: true

tooling:
  grumphp:
    description: Runs grumphp commands
    cmd:
      - appserver: ./vendor/bin/grumphp
  npm:
    description: Runs npm commands
    service: node
  xdebug-on:
    service: appserver
    description: Enables xdebug for nginx
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root
  xdebug-off:
    service: appserver
    description: Disables xdebug for nginx
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root

services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        HASH_SALT: notsosecurehash
  # chrome:
  #   type: compose
  #   services:
  #     image: selenium/standalone-chrome
  #     user: root
  #     ports:
  #       - "4444:4444"
  #     volumes:
  #       - /dev/shm:/dev/shm
  #     command: /opt/bin/entry_point.sh
  # elasticsearch:
  #   type: compose
  #   services:
  #     image: blacktop/elasticsearch:7
  #     command: /elastic-entrypoint.sh elasticsearch
  #     ports:
  #       - "9200:9200"
  #     volumes:
  #       - ./.lando/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #   # Install ES requirement JDK here & set JAVA_HOME at `.lando/.env`
  #   build_as_root:
  #     - apk --no-cache add openjdk11
  #   # Install `analysis-icu` plugin after ES service boots up
  #   run_as_root:
  #     - elasticsearch-plugin install analysis-icu
  # kibana:
  #   type: compose
  #   services:
  #     image: blacktop/kibana:7
  #     command: /docker-entrypoint.sh kibana
  #     ports:
  #       - "5601:5601"
  #     depends_on:
  #       - elasticsearch
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: node
    build:
      - npm install

proxy:
  # elasticsearch:
  #   - elasticsearch-silta.lndo.site:9200
  # kibana:
  #   - kibana-silta.lndo.site:5601
  mailhog:
    - mail-silta.lndo.site

events:
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cr -y

env_file:
  - .lando/.env

# Tested with Lando version
version: v3.0.0-rc.22
