name: silta
recipe: drupal9

config:
  php: "7.3"
  via: nginx
  webroot: web
  database: "mariadb:10.3"
  xdebug: off
  config:
    php: .lando/php.ini

tooling:
  grumphp:
    description: "Runs grumphp commands"
    cmd:
      - appserver: ./vendor/bin/grumphp
  npm:
    description: "Runs npm commands"
    service: node
  xdebug:
    description: "Loads Xdebug in the selected mode"
    cmd:
      - appserver: /app/.lando/xdebug.sh
    user: root

services:
  appserver:
    build:
      - "composer install"
    overrides:
      environment:
        HASH_SALT: notsosecurehash
        ENVIRONMENT_NAME: local
        DB_NAME_DRUPAL: drupal9
        DB_USER_DRUPAL: drupal9
        DB_PASS_DRUPAL: drupal9
        DB_HOST_DRUPAL: database
        # Support debugging with XDEBUG 3.
        XDEBUG_MODE:
        # Support debugging Drush with XDEBUG 3.
        PHP_IDE_CONFIG: serverName=appserver
  # chrome:
  #   type: compose
  #   services:
  #     image: selenium/standalone-chrome
  #     user: root
  #     ports:
  #       - "4444:4444"
  #     volumes:
  #       - /dev/shm:/dev/shm
  #     command: /opt/bin/entry_point.sh
  # elasticsearch:
  #   type: "elasticsearch:7.12.0"
  #   # Replace `true` with `9200` for proxy http://localhost:9200.
  #   portforward: true
  #   overrides:
  #     environment:
  #       ELASTICSEARCH_HEAP_SIZE: 1024m
  #       # Comma, semi-colon or space separated list of plugins to install at initialization.
  #       ELASTICSEARCH_PLUGINS: analysis-icu
  #     volumes:
  #       # Extend the default configuration with custom settings like
  #       # allowing CORS requests at `.lando/my_elasticsearch.yml`.
  #       # @see: https://github.com/bitnami/bitnami-docker-elasticsearch#configuration-file.
  #       - "./.lando/my_elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml"
  # kibana:
  #   type: compose
  #   ssl: true
  #   sslExpose: false
  #   services:
  #     image: "bitnami/kibana:7.12.0"
  #     command: "/opt/bitnami/scripts/kibana/entrypoint.sh /opt/bitnami/scripts/kibana/run.sh"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  node:
    type: "node:12"
    build:
      - "npm install"

proxy:
  mailhog:
    - mail-silta.lndo.site
  # kibana:
  #   - "kibana-silta.lndo.site:5601"

events:
  post-db-import:
    - appserver: "cd $LANDO_WEBROOT && drush cache:rebuild -y && drush @local user:login"

env_file:
  - .lando/.env

# Tested with Lando version
version: v3.1.4
