version: 2.1

orbs:
  silta: silta/silta@dev:circleci-orb

jobs:
  validate:
    executor: silta/silta

    steps:
      - checkout

      - silta/phpcs

  build:
    executor: silta/silta

    steps:
      - checkout

      - silta/drupal-composer-install

      - silta/yarn-install

      - silta/drupal-docker-build

  deploy:
    executor: silta/silta

    steps:
      - checkout

      - silta/set-release-name

      - silta/gcloud-login

      - silta/drupal-helm-deploy

workflows:
  version: 2
  commit:
    jobs:
      - validate
      - build:
          context: global_nonprod
      - deploy:
          context: global_nonprod
          requires:
            - build
